In [63]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler


In [64]:
# 读取CSV文件，不指定数据类型，让pandas自动识别
data = pd.read_csv('haiyang.csv')

missing_rows = data[data.isnull().any(axis=1)]
zero_rows = data[(data == 0).any(axis=1)]

data.fillna(0, inplace=True)

for i, name in enumerate(data.columns.tolist()):
    print(f"{i+1}  {name}: {data[data[name] != 0.0].shape}")
    print(data[name].unique(), "\n")


C:\Users\yepzvv\AppData\Local\Temp\ipykernel_1040\1457950393.py:2: DtypeWarning: Columns (11) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('haiyang.csv')


1  气压（百帕）: (779, 27)
[   0.  1003.1 1003.  1002.6 1002.5 1002.8 1006.2 1008.6 1008.5 1005.4
 1006.7 1005.9 1005.5 1006.8 1006.6 1005.  1006.3 1005.6 1004.8 1006.1
 1005.2 1006.5 1005.8 1005.3 1004.6 1007.7 1007.8 1007.6 1007.2 1007.
 1007.3 1010.1 1010.2 1009.8 1009.6 1009.9 1013.1 1009.  1009.1 1008.9
 1008.8 1017.6 1017.2 1017.1 1016.7 1016.1 1017.7 1017.3 1017.  1016.2
 1016.8 1017.4 1017.5 1016.3 1018.  1014.  1019.9 1024.2 1020.6 1023.6
 1019.1 1024.8 1015.2 1015.1 1015.5 1014.2  999.3 1006.4 1002.7 1002.4
 1002.3 1006.  1005.1 1012.7 1012.9 1012.6 1016.  1018.7 1018.6 1015.6
 1015.7 1015.4 1018.3 1017.8 1018.5 1016.9 1015.8 1014.4 1014.5 1021.4
 1021.7 1021.6 1021.1 1021.2 1023.1 1023.4 1023.  1023.3 1023.2 1021.3
 1021.5 1013.3 1012.8 1016.6 1015.9 1013.2 1021.9 1020.3 1019.3 1018.1
 1020.4 1019.5 1020.5 1019.7 1018.4 1020.9 1020.1 1018.2 1009.5 1017.9
 1018.9 1011.9 1010.  1014.7 1014.8 1015.3 1013.5 1011.5 1013.9 1013.7
 1011.4 1013.6 1012.3 1011.6 1012.4 1013.8 1019.  1025.2 

In [65]:
# non_zero_mean = data[data['气压（百帕）'] != 0]['气压（百帕）'].mean()  
# data['气压（百帕）'].replace(0, non_zero_mean, inplace=True)

# non_zero_mean = data[data['浪高(米)'] != 0]['浪高(米)'].mean()  
# data['浪高(米)'].replace(0, non_zero_mean, inplace=True)

# non_zero_mean = data[data['最小降雨量（毫米）'] != 0]['最小降雨量（毫米）'].mean()  
# data['最小降雨量（毫米）'].replace(0, non_zero_mean, inplace=True)

In [66]:
columns_to_drop = ['预报时段', '流速（米/秒）', '视程（公里）', '预报时次', '天气状况', 
                   '浪高级别', '预警信号', '写入时间', '预报时间', '主键ID', '天气图标',
                    '气压（百帕）', '最小降雨量（毫米）']
data = data.drop(columns=columns_to_drop)

for i, name in enumerate(data.columns.tolist()):
    print(f"{i+1}  {name}: {data[data[name] != 0.0].shape}")
    print(data[name].unique(), "\n")


1  区域名称: (99220, 14)
['深汕海区' '三门岛海域' '大亚湾' '大鹏湾' '妈湾蛇口海域' '机场西部海域' '深圳湾' '深圳西部沿海海域' '珠江口'] 

2  阵风（级）: (99220, 14)
['6' '6-7' '7' '5' '4-5' '5-6' '7-8' '4' '3' '6-8' '8' '3-4' '4-6' '8-9'
 '10' '8-10' '2' '9' '6-6' '11' '0' '1' '11-15' '10-14' '14-16' '12-14'
 '9-11' '10-12' '9-10' '11-13' '11-12' '56' '48' '45' '10-11' '12' '7-9'
 '13' '13-16' '44-5' '14-15' '14' '2-3'] 

3  能见度（公里）: (98644, 14)
[15 20 18 10 12 14  0  8 16 13 25  9 17 30 19  6  5  3 11  7] 

4  最大湿度（百分比）: (99178, 14)
[ 95 100  90  85  80  70  75  65  60  55  50  98  94  93  91  97  96  92
  86  79  99  88  83  81  89  82  72  62  74  66  84  64  78  87  48  40
  76  61  68  59  58  71  73  47  77  69  54  43  41  37  52  39  56   0
  67  49  45  35  53] 

5  风向: (99220, 14)
['东南' '南' '西南' '北' '东' '东北' '西北' '西' '东北转' '无' '-'] 

6  紫外线（指数）: (40035, 14)
[ 0  8  9 10 12 11  5  7  6  4  2  3  1 13] 

7  最低能见度（公里）: (98874, 14)
['10' '5' '2' '8' '3' '1' '4' '6' '7' '.5' '0' '12' '15' '14' '9' '13'
 '11' '20' '.3' '1.5' '-' 8

In [67]:
valid_values = {'6', '7', '5','4', '3', '8', 
                '10', '2', '9','11', '0', '1', '12'}
data = data[data['阵风（级）'].isin(valid_values)]
data = data[data['风力（级）'].isin(valid_values)]

valid_values = {'东南', '南', '西南', '北', '东', '东北', '西北', '西'}
data = data[data['阵风风向'].isin(valid_values)]
data = data[data['风向'].isin(valid_values)]

valid_values = {'10', '5', '8', '3', '1', '7', '4', '12', '6', '15', '14', '9', '2', '13', '11',
 '20', '1.5', 8.0, 5.0, 10.0, 7.0, 4.0, 3.0, 2.0, 6.0, 20.0, 1.0, 0.2, 15.0, 12.0, 9.0, 11.0, 0.1, 14.0, 13.0, 18.0}
data = data[data['最低能见度（公里）'].isin(valid_values)]

for i, name in enumerate(data.columns.tolist()):
    print(f"{i+1}  {name}: {data[data[name] != 0.0].shape}")
    print(data[name].unique(), "\n")

1  区域名称: (76348, 14)
['深汕海区' '三门岛海域' '大亚湾' '大鹏湾' '妈湾蛇口海域' '机场西部海域' '深圳湾' '深圳西部沿海海域' '珠江口'] 

2  阵风（级）: (76348, 14)
['6' '7' '5' '4' '3' '8' '10' '2' '9' '11' '0' '12'] 

3  能见度（公里）: (76348, 14)
[15 20 10 12 18  8 16 13 25 17 30 19 14  6  5  3  9 11  7] 

4  最大湿度（百分比）: (76348, 14)
[ 95 100  90  85  80  70  75  65  60  55  50  94  93  91  97  96  92  98
  86  79  99  88  83  81  89  82  62  74  66  84  64  87  76  61  68  59
  58  71  72  78  48  73  47  77  69  54  43  41  37  40  52  39  45  35] 

5  风向: (76348, 14)
['东南' '南' '西南' '东' '东北' '北' '西北' '西'] 

6  紫外线（指数）: (32553, 14)
[ 0  8 10 11  9  5  7  6  4  2  3  1 12 13] 

7  最低能见度（公里）: (76348, 14)
['10' '5' '8' '3' '1' '7' '4' '12' '6' '15' '14' '9' '2' '13' '11' '20'
 '1.5' 8.0 5.0 10.0 7.0 4.0 3.0 2.0 6.0 20.0 1.0 0.2 15.0 12.0 9.0 11.0
 0.1 14.0 13.0 18.0] 

8  浪高(米): (15181, 14)
[0.   1.25 0.5  1.5  2.5  0.1  9.   4.   6.   3.4  3.5 ] 

9  降雨量（毫米）: (27926, 14)
[2.00e-01 0.00e+00 4.50e+00 4.00e-01 5.00e-01 3.16e+01 1.20e+00 3.00e+

In [68]:
region_mapping = {
    '深汕海区': 1,
    '三门岛海域': 2,
    '大亚湾': 3,
    '大鹏湾': 4,
    '妈湾蛇口海域': 5,
    '机场西部海域': 6,
    '深圳湾': 7,
    '深圳西部沿海海域': 8,
    '珠江口': 9
}
data['区域名称'] = data['区域名称'].replace(region_mapping)

region_mapping = {
    '东': 1,
    '南': 2,
    '西': 3,
    '北': 4,
    '东南': 5,
    '西南': 6,
    '东北': 7,
    '西北': 8,
    '无': 9
}
data['阵风风向'] = data['阵风风向'].replace(region_mapping)
data['风向'] = data['风向'].replace(region_mapping)

region_mapping = {
    '0': 0,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10,
    '11': 11,
    '12': 12
}
data['阵风（级）'] = data['阵风（级）'].replace(region_mapping)
data['风力（级）'] = data['风力（级）'].replace(region_mapping)

region_mapping = {
    '1.5': 1.5,
    '1': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7': 7,
    '8': 8,
    '9': 9,
    '10': 10,
    '11': 11,
    '12': 12,
    '13': 13,
    '14': 14,
    '15': 15,
    '20': 20,
}
data['最低能见度（公里）'] = data['最低能见度（公里）'].replace(region_mapping)

for i, name in enumerate(data.columns.tolist()):
    print(f"{i+1}  {name}: {data[data[name] != 0.0].shape}")
    print(data[name].unique(), "\n")

1  区域名称: (76348, 14)
[1 2 3 4 5 6 7 8 9] 

2  阵风（级）: (76345, 14)
[ 6  7  5  4  3  8 10  2  9 11  0 12] 

3  能见度（公里）: (76348, 14)
[15 20 10 12 18  8 16 13 25 17 30 19 14  6  5  3  9 11  7] 

4  最大湿度（百分比）: (76348, 14)
[ 95 100  90  85  80  70  75  65  60  55  50  94  93  91  97  96  92  98
  86  79  99  88  83  81  89  82  62  74  66  84  64  87  76  61  68  59
  58  71  72  78  48  73  47  77  69  54  43  41  37  40  52  39  45  35] 

5  风向: (76348, 14)
[5 2 6 1 7 4 8 3] 

6  紫外线（指数）: (32553, 14)
[ 0  8 10 11  9  5  7  6  4  2  3  1 12 13] 

7  最低能见度（公里）: (76348, 14)
[10.   5.   8.   3.   1.   7.   4.  12.   6.  15.  14.   9.   2.  13.
 11.  20.   1.5  0.2  0.1 18. ] 

8  浪高(米): (15181, 14)
[0.   1.25 0.5  1.5  2.5  0.1  9.   4.   6.   3.4  3.5 ] 

9  降雨量（毫米）: (27926, 14)
[2.00e-01 0.00e+00 4.50e+00 4.00e-01 5.00e-01 3.16e+01 1.20e+00 3.00e+00
 5.00e+00 4.00e+00 9.60e+00 8.40e+00 4.20e+00 1.00e-01 8.00e-01 2.00e+00
 1.60e+00 3.00e-01 2.10e+00 1.00e+00 5.10e+00 3.10e+00 7.70e+00 9.00e-01

In [69]:
data
data.to_csv('preprocess1.csv', index=False)
zero_rows = data[(data == 0).any(axis=1)]

       区域名称  阵风（级）  能见度（公里）  最大湿度（百分比）  风向  紫外线（指数）  最低能见度（公里）  浪高(米)  \
0         1      6       15         95   5        0       10.0    0.0   
1         1      6       15         95   5        0       10.0    0.0   
2         1      6       15         95   2        0       10.0    0.0   
4         1      7       15         95   2        0       10.0    0.0   
5         2      6       15         95   5        0       10.0    0.0   
...     ...    ...      ...        ...  ..      ...        ...    ...   
99215     7      4       20         90   2        9       10.0    0.0   
99216     7      4       20         85   5        9       10.0    0.0   
99217     7      4       20         85   2        9       10.0    0.0   
99218     7      4       20         85   2        9       10.0    0.0   
99219     7      4       20         85   2       10       15.0    0.0   

       降雨量（毫米）  阵风风向  湿度（百分比）  最低温度（摄氏度）  风力（级）  最高温度（摄氏度）  
0          0.2     5       70         26      4         30  
1